[package]
name = "morf-io"
description = "I/O primitives for morf"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
libc.workspace = true
zbus.workspace = true
ureq.workspace = true
flate2.workspace = true
lzma-rs.workspace = true
ruzstd.workspace = true
