//! `morf types DIR`: the API as Lua language server definitions.
//!
//! Written from the engine itself -- the `morf` table a runtime installs,
//! walked, and every element's property schema -- so what an editor
//! suggests is what this build takes. The files are LuaLS `---@meta`
//! definitions: point `workspace.library` at the folder (or at the installed
//! library, which carries them) and `morf.`, `ui.Rect { ... }` and friends
//! complete and check.

use std::fmt::Write as _;

use luna::{Table, Value as LuaValue};

use crate::Runtime;

/// Tables walked this deep under `morf`; deeper ones are `table`.
const MAX_DEPTH: usize = 3;

fn is_identifier(name: &str) -> bool {
    const KEYWORDS: &[&str] = &[
        "and", "break", "do", "else", "elseif", "end", "false", "for", "function", "goto", "if",
        "in", "local", "nil", "not", "or", "repeat", "return", "then", "true", "until", "while",
    ];
    let mut chars = name.chars();
    matches!(chars.next(), Some(c) if c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
        && !KEYWORDS.contains(&name)
}

fn class_name(path: &str) -> String {
    path.split('.')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(".")
}

fn walk<'gc>(
    ctx: luna::Context<'gc>,
    out: &mut String,
    table: Table<'gc>,
    path: &str,
    depth: usize,
) {
    let mut entries = table
        .iter(ctx)
        .filter_map(|(key, value)| match key {
            LuaValue::String(key) => Some((key.display_lossy().to_string(), value)),
            _ => None,
        })
        .collect::<Vec<_>>();
    entries.sort_by(|a, b| a.0.cmp(&b.0));
    let mut nested = Vec::new();
    let _ = writeln!(out, "---@class {}", class_name(path));
    for (name, value) in &entries {
        if !is_identifier(name) {
            continue;
        }
        let kind = match value {
            LuaValue::Function(_) => "fun(...): any".to_owned(),
            LuaValue::Table(_) if depth < MAX_DEPTH => {
                nested.push(name.clone());
                class_name(&format!("{path}.{name}"))
            }
            LuaValue::Table(_) => "table".to_owned(),
            LuaValue::Boolean(_) => "boolean".to_owned(),
            LuaValue::Integer(_) => "integer".to_owned(),
            LuaValue::Number(_) => "number".to_owned(),
            LuaValue::String(_) => "string".to_owned(),
            LuaValue::UserData(_) => "any".to_owned(),
            _ => "any".to_owned(),
        };
        let _ = writeln!(out, "---@field {name} {kind}");
    }
    let _ = writeln!(out);
    for name in nested {
        if let Some((_, LuaValue::Table(child))) = entries.iter().find(|(n, _)| *n == name) {
            walk(ctx, out, *child, &format!("{path}.{name}"), depth + 1);
        }
    }
}

fn lua_type(kind: &str) -> &'static str {
    match kind {
        "number" => "number",
        "boolean" => "boolean",
        "string" => "string",
        "color" => "string|morf.Color",
        _ => "any",
    }
}

/// The definitions, as `(relative path, contents)`.
pub fn generate_types() -> Vec<(String, String)> {
    let mut runtime = Runtime::default();
    let mut morf_file = String::from(
        "---@meta\n-- Generated by `morf types` from this build of the engine; do not edit.\n\n",
    );
    runtime.lua.enter(|ctx| {
        if let Ok(morf) = ctx.get_global::<Table>("morf") {
            walk(ctx, &mut morf_file, morf, "morf", 0);
        }
    });
    morf_file.push_str(
        "---@class morf.Color\n---@field r number\n---@field g number\n---@field b number\n---@field a number\n\n\
         ---@type Morf\nmorf = {}\n\nreturn morf\n",
    );

    let mut ui = String::from(
        "---@meta\n-- Generated by `morf types` from this build of the engine; do not edit.\n\n\
         ---@class morf.Node\n---@field id string?\n\n",
    );
    let events = crate::events::EVENT_PROPERTIES
        .iter()
        .map(|(_, name)| *name)
        .collect::<Vec<_>>();
    let mut constructors = String::new();
    for (element, properties) in morf_scene::element_schemas() {
        let _ = writeln!(ui, "---@class morf.ui.{element}Props");
        let _ = writeln!(ui, "---@field [integer] morf.Node children");
        let _ = writeln!(ui, "---@field id string?");
        for key in [
            "behavior", "states", "state", "enter", "exit", "loop", "stretch", "track",
        ] {
            let _ = writeln!(ui, "---@field {key} any?");
        }
        let _ = writeln!(ui, "---@field on_destroyed (fun())?");
        for property in properties {
            if !is_identifier(property.name) {
                continue;
            }
            let kind = lua_type(property.kind);
            let _ = writeln!(
                ui,
                "---@field {} ({kind}|fun(): {kind})? default {:?}",
                property.name, property.default
            );
        }
        for event in &events {
            let _ = writeln!(ui, "---@field {event} (fun(...): any)?");
        }
        let _ = writeln!(ui);
        let _ = writeln!(
            constructors,
            "---@param props morf.ui.{element}Props\n---@return morf.Node\nfunction ui.{element}(props) end\n"
        );
    }
    ui.push_str("---@class morf.ui\nlocal ui = {}\n\n");
    ui.push_str(&constructors);
    ui.push_str("return ui\n");

    vec![
        ("morf.lua".to_owned(), morf_file),
        ("morf/ui.lua".to_owned(), ui),
    ]
}
